#pragma once

#include <driver/gpio.h>

// Recovered from trae_card 1.0.0 (2026-08-11). See README for evidence.
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_10
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_WS GPIO_NUM_3
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_2
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_4
#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_9
#define DISPLAY_SPI_SCK_PIN GPIO_NUM_8
#define DISPLAY_SPI_CS_PIN GPIO_NUM_1
#define DISPLAY_DC_PIN GPIO_NUM_20
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_21
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
